# Generated by Django 5.0.6 on 2024-10-28 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kgw_management', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kgwjobexpenses',
            name='serial_number',
        ),
    ]
