# Generated by Django 5.0.6 on 2024-10-28 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kgw_management', '0002_remove_kgwjobexpenses_serial_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kgwdailyexpense',
            name='uom',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='kgwjobexpenses',
            name='uom',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
