# Generated by Django 5.0.6 on 2024-10-28 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kgw_management', '0003_alter_kgwdailyexpense_uom_alter_kgwjobexpenses_uom'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kgwjobexpenses',
            name='job',
        ),
        migrations.AddField(
            model_name='kgwjobexpenses',
            name='job_no',
            field=models.CharField(default=1, max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
