# Generated by Django 5.0.6 on 2024-10-28 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kgw_management', '0005_remove_kgwdailyexpense_job_kgwdailyexpense_job_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kgwstuffovertime',
            name='serial_number',
        ),
        migrations.AlterField(
            model_name='kgwdailyexpense',
            name='job_no',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='kgwjobdetail',
            name='job_no',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='kgwjobexpenses',
            name='job_no',
            field=models.CharField(max_length=100),
        ),
    ]
