# Generated by Django 5.0.6 on 2024-10-28 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kgw_management', '0006_remove_kgwstuffovertime_serial_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kgwjobexpenses',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='kgwdailyexpense',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
