# Generated by Django 5.0.6 on 2024-10-28 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kgw_management', '0007_kgwjobexpenses_date_alter_kgwdailyexpense_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='kgwstuffovertime',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
