# Generated by Django 5.0.6 on 2024-11-07 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kgw_management', '0009_officemachineriesexpense'),
    ]

    operations = [
        migrations.CreateModel(
            name='KCTSellList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('invoice_no', models.CharField(max_length=50)),
                ('customer_name', models.CharField(max_length=100)),
                ('item_description', models.CharField(max_length=255)),
                ('quantity', models.IntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, max_digits=15)),
                ('note', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
