# Generated by Django 5.0.6 on 2024-11-07 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kgw_management', '0012_alter_kgwdailyexpense_detail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kgwdailyexpense',
            name='job_no',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='kgwjobexpenses',
            name='item_detail',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='kgwjobexpenses',
            name='quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='kgwjobexpenses',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='kgwjobexpenses',
            name='unit_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
